# Project
site_name: Amazon Bedrock Cookbook
copyright: Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
site_author: Bedrock-GTM
site_description: Amazon Bedrock cookbook website
# Repository
repo_name: "Github: Amazon-Bedrock-Samples"
repo_url: "https://github.com/aws-samples/amazon-bedrock-samples/tree/main"
# Plugins
plugins:
  - tags:
      tags_file: 'general/tags.md'
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags:
      tags: false
      tags_allowed:
        - Agents
        - Multi-Agent-Collaboration 
        - Knowledge-Bases
        - RAG
        - Prompt-Engineering
        - Langchain
        - LlamaIndex
        - Evaluation
        - Embedding
        - Batch-Inference
        - Fine-Tuning
        - Custom-Model-Import
        - LLM-as-Judge
        - Responsible-AI
        - Guardrails
# # extras and additional configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aws-samples/amazon-bedrock-samples/tree/main
# Theme
theme:
  name: material
  logo: logo.png
  font:
    text: Roboto
    code: Roboto Mono
  icon: 
    repo: fontawesome/brands/git-alt
  features:
    - tags
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer
    # - navigation.sections
    # - navigation.tabs
    - search.highlight
    - search.suggest
  language: en
  palette:
    - scheme: default
      primary: white
      accent: purple 
  favicon: assets/favicon.png
  
# Extensions 
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - def_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.mark

# Website Page Tree
nav:
  - Home: 'index.md'
  - Get Started: 'general/get-started.md'
  - Agents:
    - Function Calling:
      - Function Calling with Converse: './agents/function-calling/function_calling_with_converse/function_calling_with_converse.md'
      - Function Calling with Invoke: './agents/function-calling/function_calling_with_invoke/function_calling_model_with_invoke.md'
      - Return of Control: './agents/function-calling/return_of_control/return_of_control.md'
      - Tool Binding: './agents/function-calling/tool_binding/tool_bindings.md'
  - Tags: 'general/tags.md'
  - License: 'general/license.md'