AWSTemplateFormatVersion: "2010-09-09"
Description: "Supporting resources for Insurance Agent powered by Amazon Bedrock"
Metadata:
  LICENSE: >-
    Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

    Permission is hereby granted, free of charge, to any person obtaining a copy of this
    software and associated documentation files (the "Software"), to deal in the Software
    without restriction, including without limitation the rights to use, copy, modify,
    merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
    permit persons to whom the Software is furnished to do so.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
    INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
    PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
    OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Bedrock Configuration Values
        Parameters:
          - BedrockKnowledgeBaseBucket
          - BedrockKnowledgeBaseKey
          - BedrockKnowledgeBaseId
          - BedrockDataSourceId
      - Label:
          default: Code Asset S3 Bucket, Lambda Deployment Package Keys, and Lambda Layer ARNs
        Parameters:
          - ArtifactBucket
          - DataLoaderKey
          - CreateClaimKey
          - GatherEvidenceKey
          - SendReminderKey
          - PythonPandasLayerArn
          - BedrockAgentsLayerArn
      - Label:
          default: SNS Configuration Settings
        Parameters:
          - SNSEmail
    ParameterLabels:
      ArtifactBucket:
        default: your-code-assets-bucket-name
      DataLoaderKey:
        default: /agent/lambda/data-loader/loader_deployment_package.zip
      CreateClaimKey:
        default: /agent/lambda/action-groups/create_claim.zip
      GatherEvidenceKey:
        default: /agent/lambda/action-groups/gather_evidence.zip
      SendReminderKey:
        default: /agent/lambda/action-groups/send_reminder.zip
      BedrockKnowledgeBaseBucket:
        default: your-bedrock-kb-bucket-name
      BedrockKnowledgeBaseKey:
        default: your-bedrock-kb-object-key
      BedrockKnowledgeBaseId:
        default: your-bedrock-kb-id
      BedrockDataSourceId:
        default: your-bedrock-ds-id
      PythonPandasLayerArn:
        default: "arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311-Arm64:3"
      BedrockAgentsLayerArn:
        default: layer-label-cfn
      SNSEmail:
        default: "kbuilder@amazon.com"

Parameters:
  ArtifactBucket:
    Description: S3 Bucket Containing Code Assets for Data Loader and Agent Action Group Lambda Functions
    Type: String
    Default: your-code-assets-bucket-name
  DataLoaderKey:
    Description: S3 Key for Data Loader
    Type: String
    Default: /agent/lambda/data-loader/loader_deployment_package.zip
  CreateClaimKey:
    Description: S3 Key for create claim function code
    Type: String
    Default: /agent/lambda/action-groups/create_claim.zip
  SendReminderKey:
    Description: S3 Key for send reminder function code
    Type: String
    Default: /agent/lambda/action-groups/send_reminder.zip
  GatherEvidenceKey:
    Description: S3 Key for gather evidence function code
    Type: String
    Default: /agent/lambda/action-groups/gather_evidence.zip
  BedrockKnowledgeBaseBucket:
    Description: S3 Bucket Containing Bedrock Knowledge Base Assets.
    Type: String
    Default: your-bedrock-kb-bucket-name
  BedrockKnowledgeBaseKey:
    Description: S3 Object Key for claims-brief.xlsx in Bedrock Knowledge Base
    Type: String
    Default: your-bedrock-kb-object-key
  PythonPandasLayerArn:
    Description: Python Pandas Lambda Layer ARN
    Type: String
    Default: "arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311-Arm64:3"
  BedrockAgentsLayerArn:
    Description: Agents for Bedrock Lambda Layer ARN
    Type: String
  BedrockKnowledgeBaseId:
    Description: Bedrock Knowledge Base ID
    Type: String
    Default: "C1SVVCAAX3"
  BedrockDataSourceId:
    Description: Bedrock Knowledge Base Data Source ID
    Type: String
    Default: "KVP8DR71UW"
  SNSEmail:
    Description: SNS Email.
    Type: String
    Default: "kbuilder@amazon.com"

Resources:
  ExistingClaimsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-ExistingClaims
      AttributeDefinitions:
      - AttributeName: claimId
        AttributeType: S
      - AttributeName: policyId
        AttributeType: S
      KeySchema:
      - AttributeName: claimId
        KeyType: HASH
      - AttributeName: policyId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '3'
        WriteCapacityUnits: '3'
      SSESpecification:
        SSEEnabled: True

  AgentActionGroupLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${AWS::StackName}-AgentActionGroupLambdaRole
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  AgentActionGroupLambdaRoleDefaultPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub ${AWS::StackName}-AgentActionGroupLambdaRoleDefaultPolicy
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:*
              - lambda:*
              - bedrock:*
              - sns:*
              - s3:*
            Effect: Allow
            Resource: '*'        
        Version: 2012-10-17
      Roles:
        - !Ref AgentActionGroupLambdaRole

  BedrockCreateClaimFunctionPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref CreateClaimFunction
      Principal: 'bedrock.amazonaws.com'

  BedrockSendReminderFunctionPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref SendReminderFunction
      Principal: 'bedrock.amazonaws.com'

  BedrockGatherEvidenceFunctionPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref GatherEvidenceFunction
      Principal: 'bedrock.amazonaws.com'

  DataLoaderFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to initially load the claims catalog.
      FunctionName: !Sub ${AWS::StackName}-LexBedrockDataLoader
      Code: 
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref DataLoaderKey
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 20
      Handler: index.lambda_handler
      Role: !GetAtt AgentActionGroupLambdaRole.Arn
      Environment:
        Variables:
          EXISTING_CLAIMS_TABLE_NAME: !Ref ExistingClaimsTable

  LoadPlanData:
    Type: Custom::LoadDynamoDB
    Properties:
      ServiceToken: !GetAtt DataLoaderFunction.Arn

  CreateClaimFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Bedrock Insurance agent create claim function
      FunctionName: !Sub ${AWS::StackName}-CreateClaimFunction
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref CreateClaimKey
      Runtime: python3.11
      MemorySize: 512
      Timeout: 30
      Handler: create_claim.lambda_handler
      Layers:
        - !Ref PythonPandasLayerArn
        - !Ref BedrockAgentsLayerArn
      Role: !GetAtt AgentActionGroupLambdaRole.Arn
      Architectures:
        - arm64
      Environment:
        Variables:
          EXISTING_CLAIMS_TABLE_NAME: !Ref ExistingClaimsTable
          KB_BUCKET_NAME: !Ref BedrockKnowledgeBaseBucket
          KB_BUCKET_KEY: !Ref BedrockKnowledgeBaseKey
          BEDROCK_KB_ID: !Ref BedrockKnowledgeBaseId
          BEDROCK_DS_ID: !Ref BedrockDataSourceId

  SendReminderFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Bedrock Insurance agent send reminder function
      FunctionName: !Sub ${AWS::StackName}-SendReminderFunction
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref SendReminderKey
      Runtime: python3.11
      MemorySize: 512
      Timeout: 30
      Handler: send_reminder.lambda_handler
      Layers:
        - !Ref PythonPandasLayerArn
        - !Ref BedrockAgentsLayerArn
      Role: !GetAtt AgentActionGroupLambdaRole.Arn
      Architectures:
        - arm64
      Environment:
        Variables:
          EXISTING_CLAIMS_TABLE_NAME: !Ref ExistingClaimsTable
          KB_BUCKET_NAME: !Ref BedrockKnowledgeBaseBucket
          SNS_TOPIC_ARN: !Ref SNSTopic
          BEDROCK_KB_ID: !Ref BedrockKnowledgeBaseId

  GatherEvidenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Bedrock Insurance agent gather evidence function.
      FunctionName: !Sub ${AWS::StackName}-GatherEvidenceFunction
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref GatherEvidenceKey
      Runtime: python3.11
      MemorySize: 512
      Timeout: 30
      Handler: gather_evidence.lambda_handler
      Layers:
        - !Ref PythonPandasLayerArn
        - !Ref BedrockAgentsLayerArn
      Role: !GetAtt AgentActionGroupLambdaRole.Arn
      Architectures:
        - arm64

  SNSTopic:
    Type: AWS::SNS::Topic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !Ref SNSEmail
      Protocol: email
      TopicArn: !Ref SNSTopic